/** Declaration file generated by dts-gen */

declare class Instagram {
  constructor(...args: any[]);

  addComment(...args: any[]): void;

  approve(...args: any[]): void;

  block(...args: any[]): void;

  changeProfilePhoto(...args: any[]): void;

  deleteComment(...args: any[]): void;

  deleteMedia(...args: any[]): void;

  follow(...args: any[]): void;

  getActivity(...args: any[]): void;

  getChainsData(...args: any[]): void;

  getChallenge(...args: any[]): void;

  getFollowers(...args: any[]): void;

  getFollowings(...args: any[]): void;

  getHome(...args: any[]): void;

  getMediaByShortcode(...args: any[]): void;

  getMediaComments(...args: any[]): void;

  getMediaFeedByHashtag(...args: any[]): void;

  getMediaFeedByLocation(...args: any[]): void;

  getMediaLikes(...args: any[]): void;

  getPhotosByHashtag(...args: any[]): void;

  getPhotosByUsername(...args: any[]): void;

  getPrivateProfilesFollowRequests(...args: any[]): void;

  getProfile(...args: any[]): void;

  getStoryItemsByHashtag(...args: any[]): void;

  getStoryItemsByLocation(...args: any[]): void;

  getStoryItemsByReel(...args: any[]): void;

  getStoryItemsByUsername(...args: any[]): void;

  getStoryReelFeed(...args: any[]): void;

  getStoryReels(...args: any[]): void;

  getUserByUsername(...args: any[]): void;

  getUserIdPhotos(...args: any[]): void;

  ignore(...args: any[]): void;

  like(...args: any[]): void;

  locationSearch(...args: any[]): void;

  login(...args: any[]): void;

  logout(...args: any[]): void;

  markStoryItemAsSeen(...args: any[]): void;

  replayChallenge(...args: any[]): void;

  resetChallenge(...args: any[]): void;

  save(...args: any[]): void;

  search(...args: any[]): void;

  unblock(...args: any[]): void;

  unfollow(...args: any[]): void;

  unlike(...args: any[]): void;

  unsave(...args: any[]): void;

  updateChallenge(...args: any[]): void;

  updateProfile(...args: any[]): void;

  uploadPhoto(...args: any[]): void;

  uploadStory(...args: any[]): void;

}

export default Instagram;